name: Testim DB Test

on:
  push:
    branches: [main]

jobs:
  test-with-db:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h "127.0.0.1" -u root -prootpass --silent; do
            echo "Waiting for database connection..."
            sleep 3
          done

      - name: Seed DB (with user grant fix)
        run: |
          mysql -h 127.0.0.1 -u root -prootpass <<EOF
          CREATE DATABASE IF NOT EXISTS testdb;
          CREATE USER IF NOT EXISTS 'testuser'@'%' IDENTIFIED BY 'testpass';
          GRANT ALL PRIVILEGES ON testdb.* TO 'testuser'@'%';
          FLUSH PRIVILEGES;
          USE testdb;
          CREATE TABLE IF NOT EXISTS users (id INT PRIMARY KEY, name VARCHAR(100), password VARCHAR(100));
          INSERT INTO users (id, name) VALUES (1, 'Test User') ON DUPLICATE KEY UPDATE name='Test User';
          EOF

      - name: Install Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Testim CLI
        run: npm install -g @testim/testim-cli

      - name: Run Testim Test (example)
        env:
          DB_HOST: 127.0.0.1
          DB_USER: testuser
          DB_PASS: testpass
          DB_NAME: testdb
        run: |
          # Your custom test logic here
          testim --token ${{ secrets.TESTIM_TOKEN }} --project ${{ secrets.TESTIM_PROJECT_ID }} --grid "Testim-Grid" --label "MySQL DB test"
